import { paginateOptions } from "../../constants/config";

export const transactionPayload = {
  create: {
    name: "",
    roi_rate: "",
    duration: "",
    deposit_rate: "",
  },
  update: {
    sender_name: "",
    sender_email: "",
    sender_phone: "",
    sender_nrc: "",
    sender_address: "",
    sender_account_name: "",
    sender_account_number: "",
    sender_bank_branch: "",
    sender_bank_address: "",
    merchant_account_name: "",
    merchant_account_number: "",
    bank_type: "",
    package_name: "",
    package_roi_rate: "",
    package_duration: "",
    package_deposit_amount: "",
    transaction_screenshoot: "",
    transaction_type: "",
    expired_at: "",
    status: "",
    created_at: "",
    updated_at: "",
    sender_type: "",
  },
  columns: [
    { field: "id", header: "ID", sortable: true, show: true },
    { field: "sender_account_name", header: "Account Name", sortable: true, show: true },
    { field: "sender_account_number", header: "Account No.", sortable: true, show: true },
    { field: "bank_type", header: "Bank", sortable: true, show: true },
    { field: "package_deposit_amount", header: "Deposit Amount", sortable: true, show: true },
    { field: "package_roi_rate", header: "ROI Rate", sortable: true, show: true },
    { field: "status", header: "Status", sortable: true, show: true },
    { field: "created_at", header: "Deposit Date", sortable: true, show: true },
    { field: "updated_at", header: "Approve Date", sortable: true, show: true },
  ],
  paginateParams: {
    page: 1,
    per_page: paginateOptions.rows,
    columns: "id,sender_name,sender_type,sender_account_name,sender_account_number,bank_type,package_deposit_amount,package_roi_rate,sender_phone",
    search: "",
    order: "id",
    sort: "DESC",
    filter: "status",
    value: "",
  },
};
