import { paginateOptions } from "../../constants/config";

export const agentPayload = {
    create: {
        profile: "",
        first_name: "",
        last_name: "",
        dob: "",
        email: "",
        nrc: "",
        prefix: "",
        phone: "",
        nrc_front: "",
        nrc_back: "",
        passport: "",
        passport_front: "",
        passport_back: "",
        country_id: "",
        region_or_state_id: "",
        city_id: "",
        township_id: "",
        address: "",
    },
    update: {
        profile: "",
        first_name: "",
        last_name: "",
        dob: "",
        email: "",
        nrc: "",
        prefix: "",
        phone: "",
        nrc_front: "",
        nrc_back: "",
        passport: "",
        passport_front: "",
        passport_back: "",
        country_id: "",
        region_or_state_id: "",
        city_id: "",
        township_id: "",
        address: "", 
        email_verified_at: "",
        phone_verified_at: "",
        kyc_status: "",
        password: "",
        status: "",
    },
    bankAccountCreate: {
        account_name: "",
        agent_id: "",
        account_number: "",
        address: "",
        branch: ""
    },
    bankAccountUpdate: {
        account_name: "",
        agent_id: "",
        account_number: "",
        address: "",
        branch: "",
        status: "",
        default_account: ""
    },
    searchableFields: "phone,email,nrc",
    columns: [
        { field: "first_name", header: "First Name", sortable: true, show: true },
        { field: "last_name", header: "Last Name", sortable: true, show: true },
        { field: "email", header: "Email", sortable: true, show: true },
        { field: "phone", header: "Phone", sortable: true, show: true },
        { field: "nrc", header: "NRC", sortable: true, show: true },
        { field: "passport", header: "Passport", sortable: true, show: true },
        { field: "dob", header: "DOB", sortable: true, show: true },
        { field: "kyc_status", header: "KYC Status", sortable: true, show: true },
        { field: "status", header: "Status",sortable: true, show: true },
    ],
    bankAccountColumns: [
        { field: "account_name", header: "Account Name", sortable: true, show: true },
        { field: "account_number", header: "Account Number", sortable: true, show: true },
        { field: "branch", header: "Branch", sortable: true, show: true },
        { field: "address", header: "Address", sortable: true, show: true },
        { field: "status", header: "Status", sortable: true, show: true },
    ],
    paginateParams: {
        page: 1,
        per_page: paginateOptions.rows,
        columns: "phone,email,nrc,passport",
        search: "",
        order: "id",
        sort: "DESC",
        filter: "status",
        value: "",
        start_date: '',
        end_date: ''
    },
}